//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBiblio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emprestimos
    {
        public int Id { get; set; }
        public System.DateTime DataEmprestimo { get; set; }
        public Nullable<System.DateTime> DataDevolucao { get; set; }
        public int ExemplaresId { get; set; }
        public int UtentesId { get; set; }
    
        public virtual Exemplares Exemplares { get; set; }
        public virtual Utentes Utentes { get; set; }
    }
}
