//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBiblio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exemplares
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exemplares()
        {
            this.Emprestimos = new HashSet<Emprestimos>();
        }
    
        public int Id { get; set; }
        public string Cota { get; set; }
        public string Estante { get; set; }
        public bool Requisitado { get; set; }
        public int LivrosId { get; set; }
    
        public virtual Livros Livros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emprestimos> Emprestimos { get; set; }
    }
}
