//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBiblio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Livros()
        {
            this.Exemplares = new HashSet<Exemplares>();
        }
    
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Subtitulo { get; set; }
        public string Autores { get; set; }
        public string ISBN { get; set; }
        public string Editora { get; set; }
        public short Ano { get; set; }
        public byte Edicao { get; set; }
        public short NrPaginas { get; set; }
        public string Assunto { get; set; }
        public string CDU { get; set; }
        public string Obs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exemplares> Exemplares { get; set; }
    }
}
